modLoader="javafml" #mandatoryion
loaderVersion="[40,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="airdrop_supply" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Airdrop Supply" #mandatory
authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
'''
[[dependencies.airdrop_supply]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.airdrop_supply]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
