modLoader="javafml" #mandatoryion
loaderVersion="[47,)" #mandatory
license="All rights reserved"
version="1.1.1"
[[mods]] #mandatory
modId="airdrop_supply" #mandatory
version="${file.jarVersion}" #mandatory
displayName="ReAirdrop Supply" #mandatory
logoFile="icon.png"
authors="无梦之心, KL_jiana" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
'''
[[dependencies.airdrop_supply]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.airdrop_supply]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
